# Generated by Django 3.2.5 on 2021-07-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliderindex',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='index')),
            ],
        ),
        migrations.CreateModel(
            name='Automobil',
            fields=[
                ('patente', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_taller.categoria')),
            ],
        ),
    ]
