# Generated by Django 3.2.5 on 2021-07-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_taller', '0002_automobil_sliderindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='index'),
        ),
    ]
