# Generated by Django 3.2.5 on 2021-07-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_taller', '0003_automobil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobil',
            name='modelo',
            field=models.TextField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
